### PR TITLE
Update keygen page

### PR DESCRIPTION
**Pull request by johny**
This will include static files build from https://github.com/Edgeware-Network/edgeware-keygen repo, but the generated html looks a bit different vs the current page at https://edgewa.re/keygen/ therefore I hesitate to merge this...

Screen Shot 2021-04-23 at 20 34 32-fullpage

@jsteneros - last time, did you do some manual modifications to this page when we included initially? 

@thomivy @raykyri  is there any reason why this page needs to live in separate, independent package? 
If its not a problem, we should simply bring as another page on the website, then it could share all the styles and layout we have, I think porting the JS code shouldn't be a bit issue.

### CODE REVIEW

**Comment by thomivy** [comment]
@johny -- no reason at all. I'd love to see it restyled, and if we could cache the participation statistics it would be a cool slider on the main page for token distrib.

**Comment by johny** [comment]
> @johny -- no reason at all. I'd love to see it restyled, and if we could cache the participation statistics it would be a cool slider on the main page for token distrib.

Ok, we'll pull it as a task for Agency to also bring this as a part of website. Meanwhile I'll check with @jsteneros what kind of changes he did last time

**Comment by jsteneros** [comment]
I just structured the html as it was all minified before

**Comment by raykyri** [comment]
I got an "Invalid address" error when trying to convert an address on edgewa.re/keygen. The error in the stack trace looks familiar -- I think it's caused by a broken import?

image

**Comment by johny** [comment]
I'll revert this change

**Pull request merged**
